name: Comment on New PR

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = context.payload.pull_request.user.login;
            const body = `Hi @${username},

Thanks for contributing to Hookflo's Tern Project! 🙏

While we review your PR, it would mean a lot if you could consider the following to help us grow:

- ⭐ Star the project – it really helps visibility.  
- Share it with others who might find it useful.  
- Try Hookflo at [hookflo.com](https://hookflo.com) and let us know your experience.

We welcome all feedback — positive or critical.  
Your honest thoughts on what works, what’s missing, or what could be improved will directly shape the future of Hookflo.

You can also [DM me on X](https://x.com/impratj) with your experience.`;

            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
